Generating array using arange 

In [7]:
import numpy as np
arr1d = np.arange(1 , 31)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

Reshaping 1d array into 2d array

In [8]:
arr2d = arr1d.reshape(6,5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Checking size , dimension , datatype and no. of cols and rows of array

In [18]:
print(arr2d.shape)
print(arr2d.size)
print(arr2d.ndim)
print(arr2d.dtype)


(6, 5)
30
2
int64


converting one datatype to another

In [19]:
arr3 = arr1d.astype(str)
print(arr3)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30']


Aggregation functions (sum,mean,max,min,std,variance)

In [20]:
print(np.mean(arr1d))
print(np.std(arr1d))
print(np.min(arr1d))
print(np.max(arr1d))
print(np.var(arr1d))
print(np.sum(arr1d))

15.5
8.65544144839919
1
30
74.91666666666667
465


Row wise & Column wise sum

In [24]:
print("Row wise")
print(np.sum(arr2d , axis=1))
print("column wise")
print(np.sum(arr2d , axis=0))

Row wise
[ 15  40  65  90 115 140]
column wise
[ 81  87  93  99 105]


Printing index of maximum element and minimum element in array

In [35]:
print(arr2d.argmax())
print(arr2d.argmin())


29
0


Indexing & Slicing

In [37]:
print(arr1d[0:])
print(arr2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


Accessiing (19 , 20 , 24 , 25 ,29 ,30) from arr2d

In [38]:
print(arr2d[3: ,3:])

[[19 20]
 [24 25]
 [29 30]]


Boolean indexing

In [40]:
arr = np.arange(0 , 11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_index = arr % 2 == 0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [42]:
arr = arr[bool_index]
arr

array([ 0,  2,  4,  6,  8, 10])