In [1]:
import numpy as np

Arthmetic Operations

In [2]:
a1 = np.array([1,2,3,4,5,6,7,8])
a2 = np.array([9,10,11,12,13,14,15,16])

In [4]:
add = a1 + a2
add

array([10, 12, 14, 16, 18, 20, 22, 24])

In [5]:
sub = a2 - a1
sub

array([8, 8, 8, 8, 8, 8, 8, 8])

In [8]:
a1 / a2

array([0.11111111, 0.2       , 0.27272727, 0.33333333, 0.38461538,
       0.42857143, 0.46666667, 0.5       ])

In [9]:
a1 ** a2

array([              1,            1024,          177147,        16777216,
            1220703125,     78364164096,   4747561509943, 281474976710656])

Broadcasting

In [11]:
l = [1,3,5,6,7]
arr = np.array(l)
arr

array([1, 3, 5, 6, 7])

In [16]:
arr = arr + 10
arr


array([11, 13, 15, 16, 17])

Deep and Shallow copy


In [17]:
#shallow copy
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = a.copy()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = b + 10
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#deep copy
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = a
b[0] = 333
b

array([333,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [31]:
a

array([333,   1,   2,   3,   4,   5,   6,   7,   8,   9])

Matrix Operations

In [ ]:
#matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B

array([[19, 22],
       [43, 50]])

In [33]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [34]:
#transpose of matrix
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation 
 stacking array

In [36]:
a1 = np.array([1,2,3,4,5,6,7,8])
a2 = np.array([9,10,11,12,13,14,15,16])
#row wise stack
np.vstack((a1 , a2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [37]:
#column wise 
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [38]:
np.column_stack((a1, a2))

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

spliting arrays

In [50]:
a1 = np.array([1,2,3,4,5,6,7,8]).reshape(4,2)
np.split(a1,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [51]:
np.hsplit(a1 ,2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [52]:
np.vsplit(a1,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]