General Questions

In [96]:
import numpy as np
#Columns: [Age, Math Marks, Science Marks]
data = np.array([
                 [18,85,78],
                 [19,92,88],
                 [17,76,95],
                 [18,65,70],
                 [20,90,85]
                 ])

Get the shape of matrix.

In [97]:
data.shape

(5, 3)

Find the average age of students.

In [98]:
avg = np.mean(data, axis = 0)
print("Average age : " , avg[0])


Average age :  18.4


Extract Math Marks of all students.

In [99]:
data[: , 1]

array([85, 92, 76, 65, 90])

Find the highest Science mark.

In [100]:
np.max(data[:,2])

np.int64(95)

Get details of the students who scored more then 90 in Math.

In [101]:
data[data[:,1] > 90]


array([[19, 92, 88]])

Increase Math Marks of all students by 5.

In [102]:
data[: ,1]+=5
data



array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

Find how many students are younger then 19.

In [103]:
len(data[data[:,0] < 19])

3

Calculate the average marks in each subject (column_wise mean).

In [104]:
np.mean(data[:, 1:], axis=0)

array([86.6, 83.2])

Get data of students who scored at least 80 in both subjects.

In [105]:
data[(data[: , 1] >= 80) & (data[:,2] >=80)]



array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

Replace all science marks < 75 with 0

In [106]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])